### ISSUE TITLE
Pulls old terraria server version

### ISSUE THREAD

**Issue by danielkinahan** [JoshuaTheMiller/VanillaTerraria#2]
In server command
```
: version
Terraria Server v1.4.1.1
```
Current terraria client version is v1.4.2.3

**Comment by JoshuaTheMiller** [comment]
Hey @danielkinahan! I've pushed a new version of the `latest` tag to Docker Hub!

Also, I added a tag specific to this version (`trfc/vanilla-terraria:1.4.2.3`):

![image](https://user-images.githubusercontent.com/4266541/136682114-9c5c2c2b-a335-46bd-a268-aa68c9a60fc6.png)

I'd suggest using the specific tag over `latest` as per the warning recently added in this [repository's README](https://github.com/JoshuaTheMiller/Vanilla-Terraria#-a-note-on-latest).

**Comment by JoshuaTheMiller** [comment]
Also, verified locally with my own Terraria server 👍🏻
